"use client";

import { FiFileText, FiAlertTriangle, FiUserCheck, FiZap } from "react-icons/fi";

export default function TermsAndConditions() {
  const sections = [
    {
      icon: <FiUserCheck className="text-purple-400 h-5 w-5" />,
      title: "1. Account Usage & Rules",
      text: "By creating an account on our platform, you agree to provide true and accurate info. You are responsible for protecting your account credentials, secret tokens, and API access keys. Any activity performed under your account dashboard is your responsibility."
    },
    {
      icon: <FiZap className="text-purple-400 h-5 w-5" />,
      title: "2. Fair AI Use Policies",
      text: "You must not use our platform or custom AI chatbots to build illegal, deceptive, harmful, or spam applications. Attempting to bypass safety guardrails or forcefully reverse-engineer the underlying prompt compiler system is strictly prohibited."
    },
    {
      icon: <FiAlertTriangle className="text-purple-400 h-5 w-5" />,
      title: "3. Service Limits & Liability",
      text: "Our AI chatbot services are provided on an 'as-is' basis. Since AI models generate text based on abstract parameters, we are not responsible for any unexpected text hallucinations, answers, or data mistakes generated by your custom bots to your visitors."
    },
    {
      icon: <FiFileText className="text-purple-400 h-5 w-5" />,
      title: "4. Service Changes & Termination",
      text: "We maintain the right to modify or temporarily stop certain platform features to perform routine software upgrades. Accounts found violating our fair-use security terms can be suspended or removed to save server network integrity."
    }
  ];

  return (
    <div className="relative min-h-screen bg-[#070709] font-sans selection:bg-purple-500/40 selection:text-white overflow-x-hidden">
      
      {/* Verified Fixed Checkerboard Grid Overlay */}
      <div className="fixed inset-0 bg-[linear-gradient(to_right,#ffffff02_1px,transparent_1px),linear-gradient(to_bottom,#ffffff02_1px,transparent_1px)] bg-[size:32px_32px] pointer-events-none" />
      
      {/* Upper Ambient Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-[900px] h-[300px] bg-purple-950/10 rounded-full blur-[130px] pointer-events-none" />

      <main className="relative z-10 mx-auto max-w-4xl px-6 py-28 sm:py-36 space-y-20">
        
        {/* Main Spacious Header */}
        <div className="text-center space-y-4 max-w-xl mx-auto">
          <span className="inline-block rounded-full border border-zinc-800 bg-zinc-900/40 px-3.5 py-1 text-[11px] font-mono uppercase tracking-widest text-purple-400">
            Platform Rules
          </span>
          <h1 className="text-4xl font-extrabold tracking-tight text-white sm:text-5xl">
            Terms & Conditions
          </h1>
          <p className="text-[13.5px] text-zinc-500 leading-relaxed">
            Last updated: June 2026. Please read the operational rules for maintaining an active platform node.
          </p>
        </div>

        {/* Separated Breathing Cards */}
        <div className="space-y-6 mt-10">
          {sections.map((sec, idx) => (
            <div 
              key={idx}
              className="p-8 sm:p-10 rounded-2xl border border-zinc-900 bg-[#09090c]/60 shadow-xl space-y-5 transition-colors hover:border-zinc-800/80"
            >
              <div className="flex items-center gap-4 border-b border-zinc-900 pb-4">
                <div className="h-9 w-9 rounded-xl bg-zinc-950 border border-zinc-800 flex items-center justify-center">
                  {sec.icon}
                </div>
                <h2 className="text-[16px] font-bold text-zinc-100 tracking-tight">
                  {sec.title}
                </h2>
              </div>
              <p className="text-[13.5px] leading-relaxed text-zinc-400 font-normal pt-1">
                {sec.text}
              </p>
            </div>
          ))}
        </div>

      </main>
    </div>
  );
}